[project]
name = "tsschedule"
version = "0.5.0"
dependencies = [
    "smbus2 >=0.4.2",
    "astral >=3.2",
    "pytimeparse >=1.1.8",
    "pyyaml >=6.0.1",
    "scheduleparse @ git+https://github.com/trackIT-Systems/scheduleparse.git@2026.10.1",
]
requires-python = ">=3.11"

[tool.setuptools]
packages = ["tsschedule", "tsschedule.backends"]

[project.scripts]
tsscheduled = "tsschedule.scheduled:main"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
